### PR TITLE
improvement: Added error catching for abuseLimit and rateLimit. 

### PR DESCRIPTION
**Pull request by neonvoidx**
Added onRateLimit and onAbuseLimit catch for api call. If user exceeds limits, it will alert the user via console.log() and exit gracefully. Updated examples to handle this properly since data will come back undefined. Updated README to reflect this change as well.
Closes #132

### CODE REVIEW

**Comment by neonvoidx** [comment]
Getting check errors, unsure why though, it only says exit code 1.

**Comment by neonvoidx** [comment]
Seems to be Prettier adding semicolons and tabs. Do you know if there is a way around this or a way to set it up to pass checks?

**Comment by neonvoidx** [comment]
Fixed formatting errors, but I am having issues passing the tests because of the octokit import using 

`
const Octokit = require('@octokit/rest').plugin(
  require('@octokit/plugin-throttling')
)
`

**Comment by bnb** [comment]
ah, so this project uses [StandardJS](https://standardjs.com/) which is a relatively opinionated set of rules on top of [ESLint](https://eslint.org/) – it happens to be 100% incompatible with Prettier 😅

You should be able to run the linter locally, but if not you could do:

```
npm install standard -g
standard --fix
```

After you run that, there _should_ be no console output + a bunch of file changes. If there is console output, there's some changes it couldn't automatically make.

For now, I'll check out the branch and see what we can do 👍

**Comment by neonvoidx** [comment]
ah ok lol I'll give it a try.

**Comment by bnb** [comment]
Also, I was getting the `module not found` error at first – re-ran `npm install` to fetch the updated modules and it worked 👍

**Pull request closed without merging**
